-- +goose Up
INSERT INTO products (id, name, price, category, img_thumb, img_mobile, img_tablet, img_desktop) VALUES
('1', 'Waffle with Berries', 6.50, 'Waffle',
    'https://orderfoodonline.deno.dev/public/images/image-waffle-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-waffle-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-waffle-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-waffle-desktop.jpg'),
('2', 'Vanilla Bean Crème Brûlée', 7.00, 'Crème Brûlée',
    'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-desktop.jpg'),
('3', 'Macaron Mix of Five', 8.00, 'Macaron',
    'https://orderfoodonline.deno.dev/public/images/image-macaron-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-macaron-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-macaron-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-macaron-desktop.jpg'),
('4', 'Classic Tiramisu', 5.50, 'Tiramisu',
    'https://orderfoodonline.deno.dev/public/images/image-tiramisu-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-tiramisu-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-tiramisu-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-tiramisu-desktop.jpg'),
('5', 'Pistachio Baklava', 4.00, 'Baklava',
    'https://orderfoodonline.deno.dev/public/images/image-baklava-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-baklava-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-baklava-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-baklava-desktop.jpg'),
('6', 'Lemon Meringue Pie', 5.00, 'Pie',
    'https://orderfoodonline.deno.dev/public/images/image-meringue-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-meringue-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-meringue-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-meringue-desktop.jpg'),
('7', 'Red Velvet Cake', 4.50, 'Cake',
    'https://orderfoodonline.deno.dev/public/images/image-cake-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-cake-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-cake-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-cake-desktop.jpg'),
('8', 'Salted Caramel Brownie', 4.50, 'Brownie',
    'https://orderfoodonline.deno.dev/public/images/image-brownie-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-brownie-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-brownie-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-brownie-desktop.jpg'),
('9', 'Vanilla Panna Cotta', 6.50, 'Panna Cotta',
    'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-thumbnail.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-mobile.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-tablet.jpg',
    'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-desktop.jpg')
ON CONFLICT (id) DO NOTHING;

-- +goose Down
DELETE FROM products WHERE id IN ('1','2','3','4','5','6','7','8','9');
