// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID         uuid.UUID      `json:"id"`
	CouponCode sql.NullString `json:"coupon_code"`
	Total      string         `json:"total"`
	Discounts  string         `json:"discounts"`
	CreatedAt  time.Time      `json:"created_at"`
}

type OrderItem struct {
	ID        int32     `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	ProductID string    `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

type Product struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Price      string `json:"price"`
	Category   string `json:"category"`
	ImgThumb   string `json:"img_thumb"`
	ImgMobile  string `json:"img_mobile"`
	ImgTablet  string `json:"img_tablet"`
	ImgDesktop string `json:"img_desktop"`
}
