// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (coupon_code, total, discounts)
VALUES ($1, $2, $3)
RETURNING id, coupon_code, total, discounts, created_at
`

type CreateOrderParams struct {
	CouponCode sql.NullString `json:"coupon_code"`
	Total      string         `json:"total"`
	Discounts  string         `json:"discounts"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.CouponCode, arg.Total, arg.Discounts)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.Total,
		&i.Discounts,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	ProductID string    `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, coupon_code, total, discounts, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.Total,
		&i.Discounts,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT product_id, quantity
FROM order_items
WHERE order_id = $1
`

type GetOrderItemsRow struct {
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
